<?php

/**
 * Implements hook_bssync_plugin
 * @return type 
 */
function erpal_contactsync_bssync_plugin() {
  
  return array(
    'erpal_contact'  => array(
        'type'   => 'contact',
        'title'  => t('Erpal Contact Plugin'),
        'form'   => 'erpal_contactsync_plugin_form',
        'getids' => '_erpal_contactsync_getids',
        'write'  => '_erpal_contactsync_write',
        'get'    => '_erpal_contactsync_get',
    )
  );
}


function erpal_contactsync_plugin_form() {
  
  $form = array();
  $form['info'] = array(
      '#markup' => '<h2>Erpal Contact Plugin</h2>',
  );
  return $form;
}

function _erpal_contacsynct_write($id) {
  
}

function _erpal_contactsync_get($id) {
  
}