<?php
/**
* @file
* Code for the erpal_project services module.
* ERPAL projects service adds services integration to allow data transfer for apps
*/

/**
 * Implementation of hook_services_resources().
 */
function erpal_projects_service_services_resources() {
  return array(
    'project' => array(
      'retrieve' => array(
        'help' => 'Retrieves a project',
        'file' => array('file' => 'inc', 'module' => 'erpal_projects_service', 'name' => 'inc/project'),
        'callback' => '_erpal_projects_service_project_retrieve',
        'access callback' => '_erpal_projects_service_project_access',
        'access callback file' => array('file' => 'inc', 'module' => 'erpal_projects_service', 'name' => 'inc/project'),
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The id of the project to get',
            'source' => array('path' => 0),  //counted from the end, so param = 0 is the last arg in the url!
            'optional' => TRUE,
          ),          
        ),
      ),
      'index' => array(
        'help' => 'Retrieves a listing of projects',
        'file' => array('file' => 'inc', 'module' => 'erpal_projects_service', 'name' => 'inc/project'),
        'callback' => '_erpal_projects_service_project_index',
        'access callback' => 'user_access', //@todo provide a permission to access list of projects in erpal_projects_helper module
        'access arguments' => array('access content'),  //@todo see above todo
        'access callback file' => array('file' => 'inc', 'module' => 'erpal_projects_service', 'name' => 'inc/project'),
        'access arguments append' => FALSE,  //@todo what does this mean?
        'args' => array(
          array(
            'name' => 'params',
            'optional' => TRUE,
            'type' => 'array',
            'description' => 'Parameters',
            'default value' => array(),
            'source' => array('param' => 'params'),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function erpal_projects_service_ctools_plugin_api($owner, $api) {
  if ($owner == 'services' && $api == 'services') {
    return array(
      'version' => 3,
      //'file' => 'notresourcejs.services.inc', // Optional parameter to indicate the file name to load.
      //'path' => drupal_get_path('module', 'noteresourcejs') . '/includes', // If specifying the file key, path is required.
    );
  }
}

 /**
 * Implements hook_default_services_endpoint().
 */
function erpal_projects_service_default_services_endpoint() {
  $endpoint = new stdClass();
  $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
  $endpoint->api_version = 3;
  $endpoint->name = 'projects_rest';
  $endpoint->server = 'rest_server';
  $endpoint->path = 'rest/projects';
  $endpoint->authentication = array(
    'services' => 'services',
  );
  $endpoint->server_settings = array(
    'rest_server' => array(
      'formatters' => array(
        'bencode' => TRUE,
        'json' => TRUE,
        'php' => TRUE,
        'rss' => TRUE,
        'xml' => TRUE,
        'yaml' => TRUE,
        'jsonp' => FALSE,
      ),
      'parsers' => array(
        'application/json' => TRUE,
        'application/vnd.php.serialized' => TRUE,
        'application/x-www-form-urlencoded' => TRUE,
        'application/x-yaml' => TRUE,
        'multipart/form-data' => TRUE,
      ),
    ),
  );
  $endpoint->resources = array(
    'project' => array(
      'operations' => array(
        'retrieve' => array(
          'enabled' => 1,
        ),
        'index' => array(
          'enabled' => 1,
        ),
      ),
    ),
    'user' => array(
      'actions' => array(
        'login' => array(
          'enabled' => 1,
        ),
        'logout' => array(
          'enabled' => 1,
        ),
      ),
    ),
  );
  $endpoint->debug = 0;


  $endpoints[] = $endpoint;

  return $endpoints;
}