<?php
/**
 *  @file commander_shortcut_keys/commander_shortcut_keys.module
 *  @author Thiemo Müller
 *  @version 1.0
 *  
 *  Define hooks and global callbacks.
 */

define( 'MODULE_COMMANDER_SHORTCUT_KEYS_PERMISSION_USE_COMMANDS', 'use commander shortcut keys' );

/**
 * Implements hook_permission().
 */
function commander_shortcut_keys_permission() {
  
  $permissions    = array(
    
    MODULE_COMMANDER_SHORTCUT_KEYS_PERMISSION_USE_COMMANDS  => array(
      'title'           => t('Use command shortcuts'),
      'description'     => t('Allow users to generally use shortcuts that execute commands. Permissions can be refined using the permissions provided by the commander module as well as the shortcut keys module.'),
    ),
    
  );
  
  return $permissions;
  
}

/**
 *  Implements hook_shortcut_keys_shortcut_type()
 */
function commander_shortcut_keys_shortcut_keys_shortcut_type() {
  
  return array(
    
    'command'           => array(
      'name'              => t('execute a command'),
      'access arguments'  => array( MODULE_COMMANDER_SHORTCUT_KEYS_PERMISSION_USE_COMMANDS ),
    ),
    
  );
  
}