<?php
/**
 * @file
 * Code for the erpal_crm_helper module.
 * This is needed by the feature_erpal_crm
 */

/**
* Implements hook_menu
*/ 
function erpal_crm_helper_menu(){

  $items = array();
  
  require_once 'inc/config.inc';
  $config_items = _erpal_crm_helper_config_menu();
  
  $items = array_merge($items, $config_items);
  return $items;
}
  
/**
* Implements hook_permission
*/
function erpal_crm_helper_permission(){
  return array(
    'config erpal crm' => array(
      'title' => t('Administer ERPAL CRM'), 
      'description' => t('Perform administration tasks for ERPAL CRM module.'),
    ),
    'reply mails erpal crm activity' => array(
      'title'       => t('Mail reply from activity node'), 
      'description' => t('Shows a mailto reply link for the specific user on activity nodes and the commtents of such nodes.'),
    ),
    'access activities view' => array(
      'title' => t('Access activities view'), 
      'description' => t('Allows the user to access the activities view'),
    ),
  );
}
 
/**
* Implements hook_field_attach_validate
*/
function erpal_crm_helper_field_attach_validate($entity_type, $entity, &$errors) {
  if ($entity_type == 'taxonomy_term') {
    if (isset($entity->field_is_default_term)) {
      $new_errors = _erpal_crm_helper_validate_field_default_term($entity);
      $errors = array_merge($errors, $new_errors);
    }
  }
}
 
 
/**
* Implements hook_node_validate
*/
function erpal_crm_helper_node_validate($node, $form, $form_state) {
  
  if ($node->type == 'erpal_crm_activity')
    _erpal_crm_helper_crm_activity_validate($node, $form, $form_state);
  
}

/**
* Validates crm activity nodes
*/
function _erpal_crm_helper_crm_activity_validate($node, $form, $form_state) {
  $next_contact = isset($node->field_next_contact[LANGUAGE_NONE][0]['value']) ? $node->field_next_contact[LANGUAGE_NONE][0]['value'] : false;
  
  if ($next_contact) {
    //if set, it must be in the future
    $next_contact_unixtime = strtotime($next_contact);
    if ($next_contact_unixtime < time())
      form_error($form['field_next_contact'], t('If date for next contact is set, it must be in the fututre'));
  }
}

/** 
* Implements hook_view_contacts_header_content called by module erpal_basic_helper
*/
function erpal_crm_helper_view_contacts_header_content(){
  
  //link for creating an activity
  $add_erpal_activity =  _erpal_crm_helper_create_activity_link();
  
  return array(
    $add_erpal_activity,
  );
}


function _erpal_crm_helper_view_activities_header_content(){

  $add_erpal_activity =  _erpal_crm_helper_create_activity_link();
  
  $my_content = array(
    $add_erpal_activity,
  );
  
  //ask all other modules for content in the header area of the view
  $other_module_content = module_invoke_all('view_activities_header_content');
  
  $all_content = array_merge($other_module_content, $my_content);
  
  $content = '';
  foreach ($all_content as $a_content) {
    $content .= '<br>'.$a_content;
  }
  
  return $content;
}

/**
* Helper function to create new activity link
*/
function _erpal_crm_helper_create_activity_link($q_arg = false, $query_arr = array(), $title=false){
  if (!$q_arg)
    $q = current_path();
  else 
    $q = $q_arg;
  
  if (!isset($query_arr['destination']) || $q_arg)
    $query_arr['destination'] = $q;
  
  $title = t("Create new activity"); 
  return l(
    $title, "node/add/erpal-crm-activity", array(
        'query' => $query_arr,
    )
  );
}


/**
* returns the term with field_is_default_term set true within all terms in the given vocabulary
* @param $vid the vocabulary id where to search the default term in
*/
function _erpal_crm_helper_get_default_tid($vid) {

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->fieldCondition('field_is_default_term', 'value', 1);

  $result = $query->execute();
  if (!$result)
    return false;
    
  $result = array_keys($result['taxonomy_term']);
  $result = isset($result[0]) ? $result[0] : false;

  return $result;
}

/**
* Function validates that there is only on term with field_is_default_term set in the vocabulary of the given term_entitiy
*/
function _erpal_crm_helper_validate_field_default_term($term_entity) {

  $errors = array();
  //check only if the given term is set to default
  if (!isset($term_entity->field_is_default_term[LANGUAGE_NONE][0]['value']) || !$term_entity->field_is_default_term[LANGUAGE_NONE][0]['value'])
    return $errors;
  
  $vid = $term_entity->vid;
  $terms = taxonomy_get_tree($vid);
  $has_other_default = false;
  foreach ($terms as $term_obj) { //@TODO may be an entity field query would be more performant @see _erpal_crm_helper_get_default_term
    $term = taxonomy_term_load($term_obj->tid);
    if ($term->tid != $term_entity->tid) {
      $is_default = isset($term->field_is_default_term[LANGUAGE_NONE][0]['value']) ? $term->field_is_default_term[LANGUAGE_NONE][0]['value'] : false;
      if ($is_default) {
        $has_other_default = $term;
        break;
      }
    }
  }
  
  if ($has_other_default) {
    //oh, there is another term set to default, throw an error!
    $term_link = l($has_other_default->name, 'taxonomy/term/'.$has_other_default->tid);
    $errors['field_is_default_term'][LANGUAGE_NONE][0][] = array(
      'error' => 'value',
      'message' => t('Only one term in a vacabular can be set to default. Term !term_link is already set to default.', array('!term_link' => $term_link)),
    );
  }
  
  return $errors;
}

