<?php
/**
 * @file
 * Code for the erpal_crm_helper module.
 */

/**
* Implements hook_menu
*/ 
function erpal_crm_helper_menu(){

  $items = array();
  
  require_once 'inc/config.inc';
  $config_items = _erpalcrm_helper_config_menu();
  
  $items = array_merge($items, $config_items);
  return $items;
}
  
 
/**
* Implements hook_view_contacts_header_content called by module erpal_basic_helper
*/
function erpal_crm_helper_view_contacts_header_content() {
  
  //link for creating an activity
  $add_erpal_activity =  _erpal_crm_helper_create_activity_link();
  
  return array(
    $add_erpal_activity,
  );
}


function _erpal_crm_helper_view_activities_header_content()
{
  $q = current_path();
  $add_erpal_activity =  _erpal_crm_helper_create_activity_link();
  
  $my_content = array(
    $add_erpal_activity,
  );
  
  //ask all other modules for content in the header area of the view
  $other_module_content = module_invoke_all('view_activities_header_content');
  
  $all_content = array_merge($other_module_content, $my_content);
  
  $content = '';
  foreach ($all_content as $a_content) {
    $content .= '<br>'.$a_content;
  }
  
  return $content;
}

/**
* Helper function to create new activity link
*/
function _erpal_crm_helper_create_activity_link($q_arg = false, $query_arr = array())
{
  if (!$q_arg)
    $q = current_path();
  else 
    $q = $q_arg;
  
  if (!isset($query_arr['destination']) || $q_arg)
    $query_arr['destination'] = $q;
  
  return l(
    t("Create new activity"), "node/add/erpal-crm-activity", array(
        'query' => $query_arr,
    )
  );
}