<?php
$plugin = array(
  'title'     => t('Erpal template'),
  'theme'     => 'erpal_layout_template',
  'icon'      => 'erpal_layout_template.png',
  'admin css' => 'erpal_layout_template.css',
  'category'  => 'Erpal',
  'regions' => array(
    'sidebar_top'  => t('Top row'),
	'sidebar_tabs_row'  => t('Tabs row'),
	'sidebar_left'  => t('Left row'),
	'sidebar_right'  => t('Right row'),
	'sidebar_content'  => t('Content row'),
	'footer_row'  => t('Footer row'),
  ),
);


