<?php
/**
 * @file
 * Code for the erpal_spaces_helper module.
*/

/**
* Implements hook_permission
*/
function erpal_spaces_helper_permission() {
  return array(
    'access spaces view' => array(
      'title' => t('Access spaces view'), 
      'description' => t('Allows the user to access the spaces view'),
    ),
    //TASKS
    'change group audience task' => array(
      'title' => t('Change group audience task'), 
      'description' => t('Allows the user to select the groups audience on task nodes'),
    ),
    'change group content visibility task' => array(
      'title' => t('Change group content visibility task'), 
      'description' => t('Allows the user to change the group-content visibility on task nodes'),
    ),
    'choose task file to group' => array(
      'title' => t('Choose task file to group'), 
      'description' => t('If checked, user can select if a file referenced to a task will be added to the group(s) of the task. If not checked, it will be added to the group.'),
    ),
    
    //Projects
    'change group audience project' => array(
      'title' => t('Change group audience project'), 
      'description' => t('Allows the user to select the groups audience on project nodes'),
    ),
    'change group content visibility task' => array(
      'title' => t('Change group content visibility project'), 
      'description' => t('Allows the user to change the group-content visibility on project nodes'),
    ),
    'choose project file to group' => array(
      'title' => t('Choose project file to group'), 
      'description' => t('If checked, user can select if a file referenced to a project will be added to the group(s) of the project. If not checked, it will be added to the group.'),
    ),
    
    //File
    'change group audience file' => array(
      'title' => t('Change group audience file'), 
      'description' => t('Allows the user to select the groups audience on file nodes'),
    ),
    'change group content visibility task' => array(
      'title' => t('Change group content visibility file'), 
      'description' => t('Allows the user to change the group-content visibility on file nodes'),
    ),
    
    //Timetracking
    'change group audience timetracking' => array(
      'title' => t('Change group audience timetracking'), 
      'description' => t('Allows the user to select the groups audience on timetracking nodes'),
    ),
    'change group content visibility timetracking' => array(
      'title' => t('Change group content visibility timetracking'), 
      'description' => t('Allows the user to change the group-content visibility on timetracking nodes'),
    ),
  );
}

/**
* Implements hook_field_widget_form_alter
*/
function erpal_spaces_helper_field_widget_form_alter(&$element, &$form_state, $context) {

  if (isset($element['target_id']['#bundle'])) { 
    //alter the asset file
    if (isset($element['target_id'])) {
      if ($element['target_id']['#field_name'] == 'field_asset_files') {
        $bundle = $element['target_id']['#bundle'];
        _erpal_spaces_helper_file_group_handling_widget_alter($element, $bundle);
      }
    }
  }
}

/**
* add a checkbox to each delta of a field asset file to let user choose if he wants the file to be added to the group
* of the referencing node (Task or Project). This will only be shown it the user has the right "
*/
function _erpal_spaces_helper_file_group_handling_widget_alter(&$element, $node_type) {
  $type_text = false;    
  if ($node_type == 'erpal_task') $type_text = t('task');
  if ($node_type == 'erpal_project') $type_text = t('project');
  if ($node_type == 'comment_node_erpal_project') $type_text = t('project');
  if ($node_type == 'comment_node_erpal_task') $type_text = t('task');
  
  if (user_access('choose project file to group') && $type_text) {
    //if the user has the right to choose, show him a checkbox
    $element['add_to_group'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add file to !type group', array('!type' => $type_text)),
      '#weight' => 10,
      '#default_value' => isset($element['target_id']['#default_value']) && $element['target_id']['#default_value'] ? false : true,
    );
  } else {
    //if not, we hide the element and set its value to true
    $element['add_to_group'] = array(
      '#type' => 'value',
      '#value' => true,
    );
  }
  
  
  
 
}

/**
* For a tasks, if the form for inserting a new tasks is shown, we preselect the group to the group of the parent.
*/ 
function _erpal_spaces_helper_preset_parent_group_task(&$form, &$form_state) {

  $nid = $form['nid']['#value'];
  if ($nid) {  //only if node is new, preselect the group audience
    return;
  }
  
  $parent_node = _erpal_project_task_parent_from_form($form);
  
  //now prepopulate with the groups of the parent
  $group_audience = array();
  if (isset($parent_node->group_audience[LANGUAGE_NONE])) {
    foreach ($parent_node->group_audience[LANGUAGE_NONE] as $delta=>$group_arr) {
      $group_audience[$group_arr['gid']] = $group_arr['gid'];
    }
  }
  
  $form['group_audience'][LANGUAGE_NONE]['#default_value'] = $group_audience;
}

/**
* Implements hook_node_presave
*/
function erpal_spaces_helper_node_presave($node) {
  if ($node->type == 'erpal_task') {
    _erpal_spaces_helper_ensure_group_audience_task_presave($node);
    _erpal_spaces_helper_handle_asset_file_to_group($node);
  }
  if ($node->type == 'erpal_project') {
    _erpal_spaces_helper_handle_asset_file_to_group($node);
  }
}

/**
* Implements hook_entity_presave
*/
function erpal_spaces_helper_entity_presave($entity, $type) {
  if ($type == 'comment') {
    if ($entity->node_type == 'comment_node_erpal_project' || $entity->node_type == 'comment_node_erpal_task') {
      _erpal_spaces_helper_handle_asset_file_to_group($entity);
    }
  }
}

/**
* if it should, add field asset files to nodes groups
*/
function _erpal_spaces_helper_handle_asset_file_to_group($entity) {

  if (isset($entity->field_asset_files[LANGUAGE_NONE][0])) {
    foreach ($entity->field_asset_files[LANGUAGE_NONE] as $delta=>$target_id) {
      $nid = $target_id['target_id'];
      $add_to_group = $target_id['add_to_group'];
      
      if ($add_to_group) {

        if (isset($entity->node_type) && $entity->node_type = 'comment_node_erpal_project') {
          $host_node = node_load($entity->nid); //the host node of the comment where we copy the group from
        } elseif (isset($entity->type) && ($entity->type == 'erpal_task' || $entity->type == 'erpal_project')) {
          $host_node = $entity;
        } else
          return; //unknown host entity
          
        $groups = $host_node->group_audience[LANGUAGE_NONE];
        //MERGE THE GROUPS because ther could be other groups at the file that should stay!
        $file_node = node_load($nid);
        foreach ($groups as $delta=>$gid) {
          $file_node->group_audience[LANGUAGE_NONE][] = array('gid' => $gid['gid']);
        }
        
        node_save($file_node);
      }
    }
  }
}

/**
* Make sure, that if a user that has not the permnission to change the group_audience field saves a node and the field is empty, the task will be placed in the group, where the tasks parent is placed
*/
function _erpal_spaces_helper_ensure_group_audience_task_presave($node) {
  global $user;

  $field = field_info_field('group_audience');
  if (!field_access('edit', $field, 'node', $node, $user) && !$node->nid) {
    //if user has no permission to access the field, and the node is new, we set the group to the group of the parent if one is set if there is a group set
    
    //first check if task has a parent task
    $parent_node = _erpal_project_task_parent($node);  //the parent may be a task or a project
    
    if ($parent_node) {
      //get the group(s) of the project
      $project_groups = $parent_node->group_audience[LANGUAGE_NONE];
      $node->group_audience[LANGUAGE_NONE] = $project_groups;
    }
  }
}


/**
* Implements hook field access
*/
function erpal_spaces_helper_field_access($op, $field, $entity_type, $entity, $account) {
  //Task
  if (is_object($entity) && $entity_type == 'node') {
    if ($entity->type == 'erpal_task') {
      if ($op == 'edit' && $field['field_name'] == 'group_audience') {
        return user_access('change group audience task');
      }
      
      if ($op == 'edit' && $field['field_name'] == 'group_content_access') {
        return user_access('change group content visibility task');
      }
    }
    
    //Project
    if ($entity->type == 'erpal_project') {
      if ($op == 'edit' && $field['field_name'] == 'group_audience') {
        return user_access('change group audience project');
      }
      
      if ($op == 'edit' && $field['field_name'] == 'group_content_access') {
        return user_access('change group content visibility project');
      }
    }
    
    //file
    if ($entity->type == 'erpal_file') {
      if ($op == 'edit' && $field['field_name'] == 'group_audience') {
        return user_access('change group audience file');
      }
      
      if ($op == 'edit' && $field['field_name'] == 'group_content_access') {
        return user_access('change group content visibility file');
      }
    }
    
    //timetracking
    if ($entity->type == 'erpal_timetracking') {
      if ($op == 'edit' && $field['field_name'] == 'group_audience') {
        return user_access('change group audience timetracking');
      }
      
      if ($op == 'edit' && $field['field_name'] == 'group_content_access') {
        return user_access('change group content visibility timetracking');
      }
    }
  }
}