<?php

/**
 * Implements of hook_views_api().
 */
function erpal_vcard_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'erpal_vcard'),
  );
}



/**
 * Implements of hook_theme().
 */
function erpal_vcard_theme($existing, $type, $theme, $path) {
  return array(
    //the js tree
    'erpal_vcard' => array(
      'variables' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => NULL,
      ),
    ),
    'erpal_vcard_style_row' => array(
      'variables' => array(
        'view' => NULL,
        'options' => array(),
        'fields' => array(),
        'row' => array(),
      ),
    ),
  );
}


/**
 * Theme function 
 */
function theme_erpal_vcard($variables) {
  
//  dpm($variables);
  
  $output = '';
  foreach($variables['rows'] as $row) {
    $output .= $row;
  }
 
  return $output;
}

/**
 * Theme function 
 */
function theme_erpal_vcard_style_row($variables) {
  
//  dpm($variables);
  return "GFHGFHFGHFGH";
 
}
