<?php
/**
 * @file
 * Code for the erpal_basic feature.
 */

include_once('erpal_basic.features.inc');
require_once('erpal_basic.contact.communication.taxonomy.inc');

/**
 * Implements hook_form_alter().
 */
function erpal_basic_form_alter(&$form, &$form_state, $form_id) {
  // Check if form is contact form.
  if($form_id == 'erpal_contact_node_form' && empty($form['nid']['#value'])) {
    
    // Get field_phone from the global $_GET array.
    if (isset($_GET['field_phone'])) {
      $l = LANGUAGE_NONE;
      
      // Set phone value if it's not set.
      if(!isset($form['field_phone'][$l][0]['field_phone_number'][$l][0]['value']['#default_value'])) {
        $form['field_phone'][$l][0]['field_phone_number'][$l][0]['value']['#default_value'] = $_GET['field_phone'];
      }
    }
  }
  
  if ($form_id == 'system_theme_settings') {
    _erpal_basic_alter_system_theme_form($form, $form_state);
  }
}

/**
* Alters System theme form
*/ 
function _erpal_basic_alter_system_theme_form(&$form, &$form_state) {
  $form['#submit'][] = '_erpal_basic_alter_system_theme_form_submit';
}

/**
* Submit handler to alter due to @see https://drupal.org/files/issues/1087250.logo-public-filesystem.044.patch
*/
function _erpal_basic_alter_system_theme_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];
  $key = $values['var'];
  $loaded_values = variable_get($key);
  if ($file = $values['logo_upload']) {
    unset($values['logo_upload']);
    $path = 'public://' . $file->filename;
    $file->destination = $path;
    $file->status = 1;
    $file = file_copy($file, $file->destination);
    $loaded_values['default_logo'] = 0;
    $loaded_values['logo_path'] = $file->uri;
    $loaded_values['toggle_logo'] = 1;
  }
  if ($file = $values['favicon_upload']) {
    unset($values['favicon_upload']);
    $path = 'public://' . $file->filename;
    $file->destination = $path;
    $file->status = 1;
    $file = file_copy($file, $file->destination);
    $loaded_values['default_favicon'] = 0;
    $loaded_values['favicon_path'] = $file->uri;
    $loaded_values['toggle_favicon'] = 1;
  }
  
  variable_set($key, $loaded_values);
  
  cache_clear_all();
}
