<?php
/**
 * @file
 * Code for the erpal_bookmark_helper module.
 */

 /**
* Implements hook_permission
*/
function erpal_bookmark_helper_permission(){
  $permissions = array(
    'access bookmarks view' => array(
      'title' => t('Access bookmarks view'), 
      'description' => t('Allows the users to access their bookmarks view.'),
    ),    
  );
  
  return $permissions;
}
 
/**
* Implements hook_custom_node_content_block_content to provide content for the custom content block. Hook is provided by erpal_basic_helper
*/
function erpal_bookmark_helper_custom_node_content_block_content($node) {  
  $bookmark_element = _erpal_bookmark_helper_get_bookmark_flag_link_element($node);
  
  return array(
    $bookmark_element,
  );
}

/**
* Returns the flag link to bookmark content
* @TODO make configuarable which content types are flaggable, right now, all are.
*/
function _erpal_bookmark_helper_get_bookmark_flag_link_element($node) {
  $flag_link = flag_create_link('bookmark_flag', $node->nid);
  
  $element = array(
    '#markup' => $flag_link,
    '#weight' => 1,
  );
  
  return $element;
}

/**
* Implements hook_draggableviews_handler_native_arguments_alter
*/
function erpal_bookmark_helper_draggableviews_handler_native_arguments_alter(&$arguments, $view, &$form_values) {
  global $user;
  if ($view->name == 'bookmarks') {
    //alter the arguments so the dashboard view and the big view have the same order
    $arguments = array($user->uid);
  }
}