<?php
/**
 * @file
 * Code for the erpal_basic_helper module.
 */

module_load_include('inc', 'erpal_basic_helper', 'inc/config');
module_load_include('inc', 'erpal_basic_helper', 'inc/relation');
module_load_include('inc', 'erpal_basic_helper', 'inc/token');
module_load_include('inc', 'erpal_basic_helper', 'inc/field_conditions');

 
/**
* Implements hok_init
*/ 
function erpal_basic_helper_init() {
  _erpal_basic_helper_warnings();
}


/**
* Implements hook_menu
*/ 
function erpal_basic_helper_menu(){

  $items = array();
  
  //define memu items
  $items['crm/contacts/autocomplete'] = array(
    'page callback' => '_erpal_basic_helper_contacts_autocomplete',    
    'access callback' => '_erpal_basic_helper_contacts_autocomplete_access',
    'type' => MENU_CALLBACK,
  );
  
  $items['node/%node/relations/add'] = array(
    'page callback' => '_erpal_basic_helper_relation_add_page_callback',    
    'access callback' => '_erpal_basic_helper_relation_add_access',  
    'page arguments' => array(1, 'node'),
    'access arguments' => array(1, 'node'),
  );
  
  require_once 'inc/config.inc';
  $config_items = _erpal_basic_helper_config_menu();
  
  $items = array_merge($items, $config_items);
  return $items;
} 

/**
 * Implements hook_block_info().
 */
function erpal_basic_helper_block_info() {
  return array(
    'erpal_context_links_block' => array(
      'info' => t('ERPAL context links'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function erpal_basic_helper_block_view($delta = '') {  
  if ($delta == 'erpal_context_links_block') {
    $block['subject'] = t('ERPAL context links');
    $block['content'] = _erpal_basic_helper_get_erpal_context_links();
    return $block;
  }
}

/**
* Implements hook_theme
*/
function erpal_basic_helper_theme() {
  return array(
    'erpal_context_links' => array(
      'variables' => array('links' => array()),
      'template' => 'template/context_links',
    ),
  );
}

/**
* Function retrieves all context links and asks other modules for links
*/
function _erpal_basic_helper_get_erpal_context_links() {
  $links = array();
  
  //call hook to ask other modules for links
  $links = module_invoke_all('erpal_context_links');
  
  return theme('erpal_context_links', array('links' => $links));
}

/**
* Implements hook_form_alter
*/
function erpal_basic_helper_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'relation_add_block_form' || $form_id == 'erpal_basic_helper_node_relation_add_form')
    _erpal_basic_helper_relation_add_block_form_alter($form, $form_state);
  if ($form_id == 'erpal_contact_node_form') {
    _erpal_basic_helper_contact_node_form_alter($form, $form_state);    
  }

}

/**
* Alter contact node form
*/
function _erpal_basic_helper_contact_node_form_alter(&$form, &$form_state) {
  $form['#submit'][] = '_erpal_basic_helper_contact_form_submit';
  
  _erpal_basic_helper_contact_node_form_field_conditions($form, $form_state);
}

/**
*
*/
function _erpal_basic_helper_contact_form_submit($form, &$form_state) {
  _erpal_basic_helper_postprocess_conditional_fields($form, $form_state);
}


/**
* Function to manipulate fields firstname, lastname and company name because if hidden by conditional fields or form #states they are not emptied!
* May be this will be a feature, action "emptied" in conditional fields doesn't work in combination with other hidden fields
*/
function _erpal_basic_helper_postprocess_conditional_fields($form, &$form_state) {
  $values = $form_state['values'];
  
  $contact_type = $values['field_contact_type'][LANGUAGE_NONE][0]['value'];
  
  if ($contact_type == 'person') {
    unset($values['field_company_name']);
  } elseif ($contact_type == 'company') {
    unset($values['field_firstname']);
    unset($values['field_lastname']);
  }
  
  if (!isset($values['field_company_name'])) {
    //empty field company name
    $element = array('#parents' => array('field_company_name', LANGUAGE_NONE, 0, 'value'));
    form_set_value($element, '', $form_state);    
  }
  if (!isset($values['field_firstname'])) {
    //empty field firstname
    $element = array('#parents' => array('field_firstname', LANGUAGE_NONE, 0, 'value'));
    form_set_value($element, '', $form_state);    
  }
  if (!isset($values['field_lastname'])) {
    //empty field lastname
    $element = array('#parents' => array('field_lastname', LANGUAGE_NONE, 0, 'value'));
    form_set_value($element, '', $form_state);    
  }
}

/**
* Implements hook_permission
*/
function erpal_basic_helper_permission(){
  return array(
    'config erpal basic' => array(
      'title' => t('Administer ERPAL CORE'), 
      'description' => t('Perform administration tasks for ERPAL BASIC core module.'),
    ),
    'config erpal' => array(
      'title' => t('Administer ERPAL'), 
      'description' => t('Perform administration tasks for ERPAL modules.'),
    ),
    'access contact view' => array(
      'title' => t('Access contact view'), 
      'description' => t('Allows the user to access the contact view'),
    ),    
  );
}
 
/**
* This function is called by the view contacts. Links for creating some nodes are added. 
* With the hook other modules like erpal_crm could add some more links.
*/
function _erpal_basic_helper_view_contacts_header_content() {
  
  $add_erpal_contact = _erpal_basic_helper_create_contact_link();
  
  $my_content = array(
    $add_erpal_contact,
  );
  
  //ask all other modules for content in the header area of the view
  $other_module_content = module_invoke_all('view_contacts_header_content');
  
  $all_content = array_merge($other_module_content, $my_content);
  
  $content = '';
  foreach ($all_content as $a_content) {
    $content .= '<br>'.$a_content;
  }
  
  return $content;
}

/**
* Helper function to create new contact link
*/
function _erpal_basic_helper_create_contact_link($q_arg = false, $query_arr = array(), $title=false){
  if (!$q_arg)
    $q = current_path();
  else 
    $q = $q_arg;
  
  if (!isset($query_arr['destination']) || $q_arg)
    $query_arr['destination'] = $q;
  
  if (!$title)
    $title = t("Create new contact");
    
  return l(
    $title, "node/add/erpal-contact", array(
        'query' => $query_arr,
    )
  );
}

/**
* Returns all contacts for autocomplete (first used in settings to choose "my Company"
*/
function _erpal_basic_helper_contacts_autocomplete($string){
  
  $matches = array();

  //Start a query over the node table
  $query = db_select('node', 'n');
  // Select rows that match the string within type erpal_contact
  $return = $query
    ->fields('n', array('title'))
    ->fields('n', array('nid'))
    ->condition('n.title', '%' . db_like($string) . '%', 'LIKE')
    ->condition('n.type', 'erpal_contact', '=')
    ->range(0, 10)
    ->execute();
  
  // add matches to $matches  
  foreach ($return as $row) {
    $matches[check_plain($row->title)." (".$row->nid.")"] = $row->title;
  }
  
  // return for JS
  drupal_json_output($matches);
}

/**
* Validate if user has access to the autocomplete path
* If we have an own access function we could implement complex logics for access validation
*/
function _erpal_basic_helper_contacts_autocomplete_access(){
  return user_access('config erpal basic');
}

/**
* Returns all available addresses for a given contact node
*/
function _erpal_basic_helper_get_contact_adresses($contact_node, $for_options=false) {
  return _erpal_basic_helper_get_field_values('field_addresses', $contact_node, $for_options);
}

/**
* Returns all available addresses for a given contact node
*/
function _erpal_basic_helper_get_contact_phones($contact_node, $for_options=false) {
  return _erpal_basic_helper_get_field_values('field_phone', $contact_node, $for_options);
}

/**
* returns an array of all Emailaddresses of a contact node
*/
function _erpal_basic_helper_get_contact_emails($contact_node) {
  $ret = array();

  if (isset($contact_node->field_email[LANGUAGE_NONE])) {    
    $mails = $contact_node->field_email[LANGUAGE_NONE];

    foreach ($mails as $mail) {
      $mail = $mail['value'];
      
      $ret[$mail] = $mail;
    }
  }

  return $ret;
}


/**
* Returns all available phone numbers for a given contact node
*
*/
function _erpal_basic_helper_get_contact_phone($contact_node, $for_options=false) {
  return _erpal_basic_helper_get_field_values('field_phone', $contact_node, $for_options);
}

/**
* Returns values of a field collection as array of entities or as array with a string representation of this entity
* @param $for_options if true, the return value is an array with key=>value pairs (key=entity id, value=string represent. of entities)
* @param $contact_node the contact node for which the entities should be returned
* @return an array of strings or, if $for_options is false, an array of entity field_collection entities
*/
function _erpal_basic_helper_get_field_values($field_name, $contact_node, $for_options=false) {
  $values = array();

  if (!isset($contact_node->{$field_name}[LANGUAGE_NONE]))
    return $values;

  foreach ($contact_node->{$field_name}[LANGUAGE_NONE] as $entity_id) {
    $field_entity_id = $entity_id['value'];
    $field_entity = entity_load('field_collection_item', array($field_entity_id));
    $field_entity = $field_entity[$field_entity_id];

    $entity_string = module_invoke_all('entity_as_string', $field_entity); //each module shoul deliver a string representation of its entity
    
    if (isset($entity_string[0]))
      $entity_string = $entity_string[0];
    else
      $entity_string = '';
     
    if ($for_options) {
      $values[$field_entity_id] = $entity_string;
    } else {
      $values[$field_entity_id] = $field_entity;
    }
  }

  return $values;
}

/**
* Implements hook_entity_as_string provided by erpal_basic_helper module to get a string representation of all entities provided
* in this module or in features which depend on that module
*/
function erpal_basic_helper_entity_as_string($entity) {
  if ($entity->field_name == 'field_addresses') {
    $street = isset($entity->field_street[LANGUAGE_NONE]) ? $entity->field_street[LANGUAGE_NONE][0]['value'] : '';
    $zip_code = isset($entity->field_zip_code[LANGUAGE_NONE]) ? $entity->field_zip_code[LANGUAGE_NONE][0]['value'] : '';
    $country = isset($entity->field_country[LANGUAGE_NONE]) ? $entity->field_country[LANGUAGE_NONE][0]['value'] : '';
    $city = isset($entity->field_city[LANGUAGE_NONE]) ? $entity->field_city[LANGUAGE_NONE][0]['value'] : '';
    
    $terms = _erpal_basic_helper_term_references_terms($entity->field_address_type_terms);
    $address_types = implode(',', $terms);
    $entity_string = $street." - ".$zip_code." - ".$city." (".$address_types.")";
  } elseif ($entity->field_name == 'field_phone') {
    $phone_number = $entity->field_phone_number[LANGUAGE_NONE][0]['value'];

    $terms = _erpal_basic_helper_term_references_terms($entity->field_number_type_terms );
    $phone_types = implode(',', $terms);
    $entity_string = $phone_number." (".$phone_types.")";
  }

  return $entity_string;
}

/**
* returns a term reference field as array with terms instead of ids
*/
function _erpal_basic_helper_term_references_terms($term_field) {
  $type_term_ids = isset($term_field[LANGUAGE_NONE]) ? $term_field[LANGUAGE_NONE] : array();

  $terms = array();
  foreach ($type_term_ids as $delta=>$tid) {
    $tid = $tid['tid'];
    $term = taxonomy_term_load_multiple(array($tid));
    $term = $term[$tid];
    $terms[] = $term->name;
  }
  
  return $terms;
}

/**
* Function returns the address entity which has been selected in erpal_basic_helper config for "my address"
*/
function _erpal_basic_helper_get_my_address_entity() {
  return _erpal_basic_helper_return_my_value('field_addresses');
}

/**
* Get bank accounts as array of entities for a given contact
*/
function _erpal_basic_helper_get_bank_accounts($contact, $for_options) {
  $accounts = array();

  if (!isset($contact_node->field_bank_accounts[LANGUAGE_NONE]))
    return $accounts;

  foreach ($contact_node->field_bank_accounts[LANGUAGE_NONE] as $entity_id) {
    $account_entity_id = $entity_id['value'];
    $account_entity = entity_load('field_collection_item', array($account_entity_id));
    $account_entity = $account_entity[$account_entity_id];

    $bank_number = $account_entity->field_bank_number[LANGUAGE_NONE][0]['value'];
    $account_number = $account_entity->field_account_number[LANGUAGE_NONE][0]['value'];
    $bank_name = $account_entity->field_bank_name[LANGUAGE_NONE][0]['value'];

    $account_string = $account_number." - ".$bank_name." - ".$bank_number;
    
    if ($for_options) {
      $accounts[$account_entity_id] = $account_string;
    } else {
      $accounts[$account_entity_id] = $account_entity;
    }
  }
  
  return $accounts;
}

/**
* Function returns the email address entity which has been selected in erpal_basic_helper config for "my email"
*/
function _erpal_basic_helper_get_my_email_entity() {
  return _erpal_basic_helper_return_my_value('field_email');
}

/**
* Function returns the phone number entity which has been selected in erpal_basic_helper config for "my phone"
*/
function _erpal_basic_helper_get_my_phone_entity() {
  return _erpal_basic_helper_return_my_value('field_phone');
}

/**
* Checks if the given company is the own company
* @param $contact a contact node or a contact nid
*/
function _erpal_basic_helper_is_own_company($contact) {
  if (is_numeric($contact))
    $contact_nid = $contact;
  elseif (is_object($contact))
    $contact_nid = $contact->nid;
    
  $my_company_nid = _erpal_basic_helper_get_own_company_nid(false);  

  return $contact_nid == $my_company_nid;
}

/**
* Function to return an entity (in most cases out of multiple field values) that has be definied as the main value
* @param $field_name the name of the field for which a value should be returned. CAUTION: Field must be a field_collection_item!
*/
function _erpal_basic_helper_return_my_value($field_name) {

  $my_company_nid = _erpal_basic_helper_get_own_company_nid(false);  
  
  if (!$my_company_nid)
    return false;
  
  $my_company_node = node_load($my_company_nid);
  
  //does the company have value set for this field?
  $my_value_id = 0;
  if (isset($my_company_node->{$field_name}[LANGUAGE_NONE])) {
    //does this company have only one value set? 
    if (count($my_company_node->{$field_name}[LANGUAGE_NONE]) == 1) {
      //it must be this value!
      $my_value_id = $my_company_node->{$field_name}[LANGUAGE_NONE][0]['value'];      
    }
  }
  
  if (!$my_value_id) {
    $my_value_id = variable_get('my_'.$field_name, $my_value_id);
  }
   
  if (!$my_value_id)
    return false;
  

  if (intval($my_value_id)."" == $my_value_id) { //check that it is integer, otherwise return the value
    $my_value_entity = entity_load('field_collection_item', array($my_value_id));
    $my_value_entity = $my_value_entity[$my_value_id];    
  } else
    $my_value_entity = $my_value_id;
  
  return $my_value_entity;
}

/**
* Function that returns if we are in debug mode
*/
function erpal_debug() {
  $debug = variable_get('erpal_debug', 0);
  return $debug;
}

/**
* Shows sytem warnings on if config variables are not set
*/
function _erpal_basic_helper_warnings() {
  $my_company_nid = _erpal_basic_helper_get_own_company_nid(false);
  
  if (!$my_company_nid)
    drupal_set_message(t('Please complete !config_link to make ERPAL work.', array('!config_link' => l(t('config settings'), 'admin/erpal/basic'))), 'warning');
    
  //check if private directory is set.
  $private_path = _erpal_basic_helper_private_file_path();
  _erpal_basic_helper_private_file_path();
  if (!$private_path) {
    drupal_set_message(t('To make ERPAL work with files please set your private files directory in !files_link', array('!files_link' => l(t('File system settings'), 'admin/config/media/file-system'))), 'warning');
  }
}

/**
* Returns the private file path
*/
function _erpal_basic_helper_private_file_path() {
  return variable_get('file_private_path', false);
}

/**
* returns the date format for displaying date only
*/
function _erpal_basic_helper_date_format_date_only() {
  return variable_get('erpal_date_format_date_only', 'short');
}

/**
* returns the date format for displaying date only
*/
function _erpal_basic_helper_date_format_date_time() {
  return variable_get('erpal_date_format_date_time', 'short');
}

/**
* Returns all available date formats
*/
function  _erpal_basic_helper_get_date_formats() {
  // Get list of all available date formats.  (Mostly copied from system.admin.inc
  $formats = array();
  drupal_static_reset('system_get_date_formats');
  $date_formats = system_get_date_formats(); // Call this to rebuild the list, and to have default list.
  foreach ($date_formats as $type => $format_info) {
    $formats = array_merge($formats, $format_info);
  }
  $custom_formats = system_get_date_formats('custom');
  if (!empty($custom_formats)) {
    $formats = array_merge($formats, $custom_formats);
  }
  $choices = array();
  foreach ($formats as $f => $format) {
    $choices[$f] = format_date(REQUEST_TIME, 'custom', $f);
  }
  
  return $choices;
}

/**
* Helper function to get the title of a node
* @param $nids a single nid or an array with nids
* @return an array with key = nid and value = title
*/
function _erpal_basic_helper_node_titles($nids) {
  if (is_numeric($nids))
    $nids = array($nids);
  
  $query = db_select('node', 'n');
  $query
    ->fields('n', array('nid', 'title'))
    ->condition('n.nid', $nids)
    ->addTag('node_access');
  
  $result = $query->execute();
  
  $nodes = array();
  foreach ($result as $record) {
    $nodes[$record->nid] = $record->title;
  }  
  
  return $nodes;
}

/**
* Bulk operation to delete nodes
* @param $nids array of nids to be deleted
*/
function _erpal_basic_helper_bulk_delete($nids, $redirect) {
  
  //build operation for every entity type
  $operations = array();
  $total_count = 0;
  foreach ($nids as $type=>$ids) {
    $total_count += count($ids);
    if ($total_count)
      $operations[] = array('_erpal_basic_helper_bulk_delete_operation', array($ids, $type, $total_count));
  }
  
  $batch = array(
    'operations' => $operations,
    'title' => t('Processing Delete Batch'),
    'init_message' => t('Delete Batch is starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Delete Batch has encountered an error.'),
  );
  
   
  batch_set($batch);

  batch_process($redirect); //return to the parent
}

/**
* Start bulk delete operation
* @param $nids array of entity ids that will be deleted
*/
function _erpal_basic_helper_bulk_delete_operation($nids, $entity_type, $total_count, &$context) {
  if (!isset($context['sandbox']['progress'])) {  
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['nids'] = $nids;
    $context['sandbox']['last_delta'] = -1;
    $context['sandbox']['max'] = isset($context['sandbox']['max']) ? $context['sandbox']['max'] : $total_count;
  }
 
  $nids = $context['sandbox']['nids'];
  $delta = $context['sandbox']['last_delta'] +1;

  if (isset($nids[$delta])) {
    $nid = $nids[$delta];
    
    if ($entity_type == 'node')
      node_delete($nid);
    else
      entity_delete($entity_type, $nid);
         
    $context['sandbox']['last_delta'] = $delta;
  }
 
  $context['sandbox']['progress']++;
  $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];

}

/**
* Function to bulk update nodes
* @param $callback a function as string that is called on each node update to set values of the updated node.
*/
function _erpal_basic_helper_bulk_update($nids, $callback, $args, $redirect) {
  $batch = array(
    'operations' => array(
      array('_erpal_basic_helper_bulk_update_operation', array($nids, $callback, $args)),
    ),
    'title' => t('Processing Update Batch'),
    'init_message' => t('Update Batch is starting.'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('UPdate Batch has encountered an error.'),
  );
  batch_set($batch);

  batch_process($redirect); //return to the parent
}

function _erpal_basic_helper_bulk_update_operation($nids, $callback, $args, &$context) {
  if (!isset($context['sandbox']['progress'])) {  
    $context['sandbox']['progress'] = 0;
    $context['sandbox']['nids'] = $nids;
    $context['sandbox']['last_delta'] = -1;
    $context['sandbox']['max'] = count($nids);
  }
 
  $nids = $context['sandbox']['nids'];
  $delta = $context['sandbox']['last_delta'] +1;
  
  if (!$context['sandbox']['max']) {
    $context['finished'] = true;
    return;
  }
    
  if (isset($nids[$delta])) {
    $nid = $nids[$delta];
    
    $node = node_load($nid);
   
    if (function_exists($callback)) {
      call_user_func($callback, $node, $args);
    }
    
    node_save($node);
    
    $context['sandbox']['last_delta'] = $delta;
  }
  
  $context['sandbox']['progress']++;
  $context['finished'] = $context['sandbox']['progress'] / $context['sandbox']['max'];
}

/**
* returns an array of direct children nids of a node using field_parent
* @param $nid the parent nid to search children for
* @param $types only those node types are returned
*/
function _erpal_basic_helper_get_direct_children($nid, $types=array(), $order_field=false) {
  
  $children = array();
  if (!count($types))
    return $children;
 
  foreach ($types as $type) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type)
    ->fieldCondition('field_parent', 'target_id', $nid, '=')
    ->addMetaData('account', user_load(1)); // run the query as user 1

    if ($order_field)
      $query->fieldOrderBy($order_field, 'value', 'asc');
    
    $result = $query->execute();
    if (isset($result['node'])) {
      $new_nids = array_keys($result['node']);
      $children = array_merge($children, $new_nids);
    }
  }
  
  return $children;
}

/**
* Returns an array of nids (the same as in the given array) ordered by the given field field
*/
function _erpal_basic_helper_get_ordered_nids_by_weight($nids, $order_field) {
  
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')   
    ->propertyCondition('nid', $nids, 'IN')
    ->fieldOrderBy($order_field, 'value', 'ASC');
  $result = $query->execute();
  
  $ordered_nids = array();
  if (isset($result['node'])) {
    $ordered_nids = array_keys($result['node']);
  }

  return $ordered_nids;
}

/**
* Returns the vid set as vocabulary of a term reference field
*/
function _erpal_basic_helper_term_field_get_vid($field_name) {
  $field_info = field_info_field($field_name);
  $vocabulary_name = $field_info['settings']['allowed_values'][0]['vocabulary'];
  $taxonomy = taxonomy_vocabulary_machine_name_load($vocabulary_name);
  $vid = $taxonomy->vid;
  
  return $vid;
}

/**
* returns the term with field_is_default_term set true within all terms in the given vocabulary
* @param $vid the vocabulary id where to search the default term in
*/
function _erpal_basic_helper_get_default_tid($vid) {

  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->propertyCondition('vid', $vid)
    ->fieldCondition('field_is_default_term', 'value', 1);

  $result = $query->execute();
  if (!$result)
    return false;
    
  $result = array_keys($result['taxonomy_term']);
  $result = isset($result[0]) ? $result[0] : false;

  return $result;
}

/**
* Gets all child nodes of a given parent by deepsearch.
* @return a flat array with all children nids in deep search order, each node in an array whith key 'child' and 'parent'
* @param $types the node types that should be returned and deep searched as children
*/
function _erpal_basic_helper_get_all_child_nids_deep_search($nid, $types=array()) {
  $children = _erpal_basic_helper_get_direct_children($nid, $types);
 
  $all_children = array();
  foreach ($children as $delta=>$child_nid) {    
    $sub_children = _erpal_basic_helper_get_all_child_nids_deep_search($child_nid, $types);
    $all_children[] = array('parent' => $nid, 'child' => $child_nid);
    $all_children = array_merge($all_children, $sub_children);
  }
  
  return $all_children;
}

function _erpal_basic_helper_relation_add_link($node) {
  return l('Add new relation', 'node/'.$node->nid.'/relations/add');
}

/**
* Returns the semantic status of a term reference field of a given node, a status of the allowed values of field_simple_process_status
* @param the node where the field with the status term is attached to
* @param $field_name the name if the field that contains the term id of the status term we want to analyse the semantic meaning
* @return boolean value
*/
function _erpal_basic_helper_get_tid_semantic($node, $field_name) {
  $status_tid = isset($node->{$field_name}[LANGUAGE_NONE][0]['tid']) ? $node->{$field_name}[LANGUAGE_NONE][0]['tid'] : false;
  
  if ($status_tid) {
    $term = taxonomy_term_load($status_tid);
    //get the semantic field
    $semantic_status = isset($term->field_simple_process_status[LANGUAGE_NONE][0]['value']) ? $term->field_simple_process_status[LANGUAGE_NONE][0]['value'] : false;
    return $semantic_status;
  } else
    return false;
}

/**
* Checks, if a vocabulary has at least one term with one allowed value of the given field, so that all allowed values are used
* @param $vocab_name the vocabulary machine name in which we check the terms. This vocabulary must have the field $field_name attached
* @param $field_name this is the name of the field where we get the allowed values from and check them
* @return an array with values from $field_name 's allowed values that are not used at terms in the vocabulary
*/
function _erpal_basic_helper_check_all_allowed_values_used_in_vocabulary($vocab_name, $field_name) {
  $vocabulary = taxonomy_vocabulary_machine_name_load($vocab_name);
  $field_info = field_info_field($field_name);
  
  $allowed_values = is_array($field_info['settings']['allowed_values']) ? $field_info['settings']['allowed_values'] : array();
  
  $terms = taxonomy_get_tree($vocabulary->vid);
  
  //now check if all allowed values are covered by the terms
  foreach ($terms as $term) {
    $term = taxonomy_term_load($term->tid);
    $field_value = $term->{$field_name}[LANGUAGE_NONE][0]['value'];

    if (isset($allowed_values[$field_value]))
      unset($allowed_values[$field_value]);
  }

  //now each value available in array "allowed values" has not been found in term usage of the terms of the vocabulary
  return $allowed_values;
}

/**
* Shows warnings for results of @see _erpal_basic_helper_check_all_allowed_values_used_in vocabulary
*/
function _erpal_basic_helper_warn_semantic_not_covered_by_terms($vocab_name, $field_name) {
  $semantics_not_used = _erpal_basic_helper_check_all_allowed_values_used_in_vocabulary($vocab_name, $field_name);
  
  $vocabulary = taxonomy_vocabulary_machine_name_load($vocab_name);

  $vocab_link = l($vocabulary->name, 'admin/structure/taxonomy/'.$vocabulary->machine_name);
  foreach ($semantics_not_used as $key=>$value) {
    drupal_set_message(t('The value %value is not used by any term of vocabulary !vocab_link. May be there appear some problems while using ERPAL.', array('%value' => $value, '!vocab_link' => $vocab_link)), 'warning');
  }
}

/**
* Function validates that there is only on term with field_is_default_term set in the vocabulary of the given term_entitiy
*/
function _erpal_basic_helper_validate_field_default_term($term_entity) {

  $errors = array();
  //check only if the given term is set to default
  if (!isset($term_entity->field_is_default_term[LANGUAGE_NONE][0]['value']) || !$term_entity->field_is_default_term[LANGUAGE_NONE][0]['value'])
    return $errors;
  
  $vid = $term_entity->vid;
  $terms = taxonomy_get_tree($vid);
  $has_other_default = false;
  foreach ($terms as $term_obj) { //@TODO may be an entity field query would be more performant @see _erpal_crm_helper_get_default_term
    $term = taxonomy_term_load($term_obj->tid);
    if ($term->tid != $term_entity->tid) {
      $is_default = isset($term->field_is_default_term[LANGUAGE_NONE][0]['value']) ? $term->field_is_default_term[LANGUAGE_NONE][0]['value'] : false;
      if ($is_default) {
        $has_other_default = $term;
        break;
      }
    }
  }
  
  if ($has_other_default) {
    //oh, there is another term set to default, throw an error!
    $term_link = l($has_other_default->name, 'taxonomy/term/'.$has_other_default->tid);
    $errors['field_is_default_term'][LANGUAGE_NONE][0][] = array(
      'error' => 'value',
      'message' => t('Only one term in a vacabular can be set to default. Term !term_link is already set to default.', array('!term_link' => $term_link)),
    );
  }
  
  return $errors;
}

/**
* Function that returns an array useful for select box with nid and title from nid array
*/
function _erpal_basic_helper_nids_for_form_select($nids) {
  //make a query with nid and title, its more performant to load all the possible nodes!  
  $result = array();
  if (count($nids)) {
    $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title'))
    ->condition('nid', $nids, 'IN');
    
    $result = $query->execute()
    ->fetchAll();
  }
  
  $matches = array();
  foreach ($result as $row) {
    $matches[check_plain($row->title)." (".$row->nid.")"] = $row->title;
  }
  
  return $matches;
}