<?php
/**
* @file
* Code for the erpal_hacks_helper module.
*/

/**
* Implements hook_node_form_alter
*/
function erpal_hacks_helper_form_alter(&$form, &$form_state, $form_id) {
  _erpal_hacks_fix_editablefields_problem($form);
  _erpal_hacks_fix_quick_tabs_exposed_filter_form_action($form);
}

/**
* Editable fields seams not to work, when the submit button with ajax processing inserted by editbale fields module is in subarray [actions] it will not be rendered (after that it will be removed by editable fields ajax, but submithandler will stay), so we just move it to another subarray
*/
function _erpal_hacks_fix_editablefields_problem(&$form) {
  if (isset($form['#form_id']) && $form['#form_id'] && strpos($form['#form_id'], 'editablefields_form') !== false) {
    //this is a editbale fields form
    $form['actions_hack_editable'] = $form['actions'];
    unset($form['actions']);
  }
}

/**
* If we have views (pane or block) with exposed filter embedded in quicktabs and these quicktabs in a panel, the action of the filter form is not set which redirects to the frontpage after submitting a views exposed filter form. So we set the action to the current page here
*/
function _erpal_hacks_fix_quick_tabs_exposed_filter_form_action(&$form) {
  if (isset($form['#form_id']) && $form['#form_id'] == 'views_exposed_form') {
    //only form task views
    if (in_array('views_exposed_form__tasks', $form['#theme']) || in_array('views_exposed_form__tickets', $form['#theme'])) {
      $url = $_GET['q'];
      //dpm(request_path());
      $form['#action'] = '/'.$_GET['q'];

      _erpal_hacks_helper_add_qt_parameters_to_exposed_form($form);
    }
  }
}

/**
* Adds the quicktabs current tab values to the filter, so they are kept persistent in the url during exposed filter submit
*/
function _erpal_hacks_helper_add_qt_parameters_to_exposed_form(&$form) {
  
  foreach ($_GET as $name => $value) {
    $pos = strpos($name, 'qt-');
    if ($pos === 0) {
      //this is a qucick tab current-tab parameter
      $form[$name] = array(
        '#type' => 'hidden',
        '#default_value' => $value,
      );
    }
  }
}